//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Client.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_ClientTYPE                  129
#define IDD_BUILD                       131
#define IDR_MENU_REPORT                 131
#define IDD_FILE                        132
#define IDR_LIST                        133
#define IDC_DRAG                        134
#define IDC_MUTI_DRAG                   135
#define IDC_CURSOR3                     136
#define IDC_CURSOR4                     137
#define IDD_SETTINGS                    140
#define IDD_UPDATE_DLG                  144
#define IDR_FILEMANAGER                 146
#define IDR_TOOLBAR1                    147
#define IDB_TOOLBAR                     149
#define IDB_TOOLBAR_ENABLE              149
#define IDR_TOOLBAR2                    154
#define IDR_LOCAL_VIEW                  156
#define IDR_REMOTE_VIEW                 157
#define IDB_TOOLBAR_DISABLE             158
#define IDD_TRANSFERMODE_DLG            159
#define IDD_SCREENSPY                   160
#define IDD_DOWNEXEC                    162
#define IDD_WEBCAM                      163
#define IDI_WEBCAM                      164
#define IDB_ARROWDOWN                   165
#define IDB_ARROWUP                     166
#define IDD_KEYBOARD                    167
#define IDD_NEWFOLDER                   168
#define IDD_SYSTEM                      169
#define IDR_PSLIST                      170
#define IDD_SHELL                       171
#define IDR_BSS                         173
#define IDI_CMDSHELL                    177
#define IDI_KEYBOARD                    178
#define IDI_SYSTEM                      179
#define IDC_DOT                         182
#define IDR_MINIMIZE                    183
#define IDD_AUDIO                       184
#define IDI_AUDIO                       185
#define IDD_ATTACK_DLG                  187
#define IDD_DDOS_FLOOD                  187
#define IDI_IPS                         187
#define IDR_SKIN                        188
#define IDD_DDOS_WEB                    188
#define IDI_OS                          188
#define IDI_SHIPIN                      189
#define IDI_CPU                         189
#define IDI_USER                        190
#define IDI_MEMORY                      190
#define IDI_EVENT_INFO                  191
#define IDR_MENU_DDOS                   191
#define IDI_DISK                        191
#define IDI_EVENT_ERROR                 192
#define IDD_SETTING                     192
#define IDI_USERNAME                    192
#define IDR_LOG                         193
#define IDR_TOOLBAR3                    193
#define IDI_TIME                        193
#define IDR_UPX                         194
#define IDR_ADSL_COPY                   194
#define IDD_DDOS_DRDOS                  195
#define IDB_BITMAP1                     196
#define IDD_SOCKS                       196
#define IDI_DOUBLE                      196
#define IDD_SYSINFO                     197
#define IDI_ICON_TOOL                   199
#define IDD_MORE_CHOOSE                 199
#define IDI_ICO                         200
#define IDI_MD5                         201
#define IDD_RIZHI                       202
#define IDD_ATTACK_DIALOG               202
#define IDD_IPUPDATR                    203
#define IDD_IPUPDATE                    203
#define IDI_ICON_NET_USER               204
#define IDD_CUSTOMATTACK_DIALOG         204
#define IDI_ICOINFO_PROCESS             205
#define IDI_ICOINFO_APPWIN              206
#define IDD_REG_DIALOG                  206
#define IDD_ADD_USER                    208
#define IDI_ICON_DIALU                  208
#define IDI_ICOFILE                     209
#define IDB_BAR                         211
#define IDR_REGT_MENU                   211
#define IDD_BTACK_DIALOG                212
#define IDR_REGL_MENU                   213
#define IDR_BATCH_MENU                  214
#define IDB_BUILD                       218
#define IDB_SETTING                     219
#define IDR_TAB                         220
#define IDD_DDOS                        222
#define IDI_ICON1                       223
#define IDI_ICON_DDOS                   223
#define IDR_SLIST                       225
#define IDD_CHANGE_GROUP                226
#define IDR_WLIST                       226
#define IDC_MESSAGEBAR_WARNING          226
#define IDD_TOOLS_DIALOG                227
#define IDR_WLIST1                      227
#define IDR_ILIST                       227
#define IDD_REGDATA_DLG                 227
#define IDB_Tools1                      227
#define IDI_ANTI                        227
#define IDI_REG_ICON                    228
#define IDB_Tools2                      228
#define IDI_STR_ICON                    229
#define IDR_TOOLBAR4                    229
#define IDI_FATHER_ICON                 231
#define IDB_BARNEW                      231
#define IDI_DWORD_ICON                  232
#define IDD_BUILD_SERVER                233
#define IDI_DIR_ICON                    233
#define IDD_PROXY                       238
#define IDD_TEST                        239
#define IDD_SHORTCUTS                   239
#define IDD_FLOWATTACK_DIALOG           240
#define IDD_DLLDLG                      241
#define IDD_DDOS_FLOOD1                 242
#define IDD_DDOS_WEB1                   243
#define IDD_DIALOG_DDOS                 245
#define IDD_DIALOG_DDOS_WEB             246
#define IDD_DIALOG_DDOS_DIY             247
#define IDD_DIALOG_DDOS_PF              248
#define IDD_DIALOG_ATTACK               249
#define IDR_TabCtrl                     263
#define IDR_MENU_OPTIONS                316
#define IDC_LIST_TARGET                 1002
#define IDC_TARGET_WEB                  1003
#define IDC_ATTCKPORT                   1004
#define IDC_LIST_REMOTE                 1005
#define IDC_THREADNUMS                  1005
#define IDC_LIST_LOCAL                  1006
#define IDC_LOCAL_PATH                  1007
#define IDC_HOSTNUMS                    1007
#define IDC_REMOTE_PATH                 1008
#define IDC_SLIDER_THREAD               1008
#define IDC_STATIC_REMOTE               1009
#define IDC_ATTACKTIMES                 1009
#define IDC_CONFIRM                     1010
#define IDC_SLIDER_TIME                 1010
#define IDC_PORT                        1011
#define IDC_LISTEN_PORT                 1011
#define IDC_SPIN_NUM                    1011
#define IDC_OVERWRITE                   1012
#define IDC_CONNECT_MAX                 1012
#define IDC_NEWAUTO                     1012
#define IDC_BUTTON_BEGIN                1012
#define IDC_ADDITION                    1013
#define IDC_SELECTHOST                  1013
#define IDC_PASS                        1013
#define IDC_COMBO_DNSIP                 1013
#define IDC_JUMP                        1014
#define IDC_ADDTASK                     1014
#define IDC_SEND_RATE                   1014
#define IDC_BUTTON_STOP                 1014
#define IDC_OVERWRITE_ALL               1015
#define IDC_COMBO_MODEL                 1015
#define IDC_ADDITION_ALL                1016
#define IDC_STARTVAR                    1016
#define IDC_SPIN_RATE                   1016
#define IDC_JUMP_ALL                    1017
#define IDC_ENDVAR                      1017
#define IDC_EDIT_PORT                   1017
#define IDC_CANCEL                      1018
#define IDC_EDIT_TIME                   1018
#define IDC_TIPS                        1019
#define IDC_STATIC_TIP                  1020
#define IDC_EDIT_DECIMAL                1021
#define IDC_HOST1                       1021
#define IDC_ENCODE                      1022
#define IDC_DNS_STRING                  1022
#define IDC_EDIT_HEX                    1022
#define IDC_REMOTE_HOST                 1023
#define IDC_HOST2                       1023
#define IDC_REMOTE_PORT                 1024
#define IDC_STATIC_2                    1024
#define IDC_HOST3                       1024
#define IDC_PROXY_HOST                  1025
#define IDC_STATIC_1                    1025
#define IDC_EDIT_ADDR                   1025
#define IDC_PROXY_PORT                  1026
#define IDC_STATIC_3                    1026
#define IDC_EDIT_ZDY                    1026
#define IDC_PROXY_USER                  1027
#define IDC_STATIC_4                    1027
#define IDC_PROXY_PASS                  1028
#define IDC_STATIC_6                    1028
#define IDC_EDIT_DNSUSER                1028
#define IDC_EDIT                        1029
#define IDC_STATIC_7                    1029
#define IDC_EDIT_DNSPASS                1029
#define IDC_RESETPORT                   1030
#define IDC_APPLY                       1030
#define IDC_STATIC_8                    1030
#define IDC_EDIT_DNSDOMAIN              1030
#define IDC_FOLDERNAME                  1031
#define IDC_STATIC_9                    1031
#define IDC_BTN_DNSUPDATE               1031
#define IDC_STATIC_10                   1032
#define IDC_RADIO_UDP                   1032
#define IDC_STATIC_11                   1033
#define IDC_RADIO_TCP                   1033
#define IDC_LIST_PROCESS                1034
#define IDC_TAB                         1035
#define IDC_EDIT_TIP                    1035
#define IDC_LIST_WINDOWS                1036
#define IDC_STATIC_20                   1036
#define IDC_LIST_DIALUPASS              1037
#define IDC_START_ATTACK                1037
#define IDC_EDIT_S1                     1037
#define IDC_BUILD                       1038
#define IDC_START_STOP                  1038
#define IDC_EDIT_S2                     1038
#define IDC_RADIO_SJLU                  1039
#define IDC_CONNECT_AUTO                1040
#define IDC_STATIC_VER                  1041
#define IDC_ENABLE_HTTP                 1043
#define IDC_EDIT_BAO                    1043
#define IDC_RADIO_ANSI                  1043
#define IDC_EDIT_REVC                   1044
#define IDC_RADIO_HEX                   1044
#define IDC_CHECK_AUTH                  1048
#define IDC_CHECK_PROXY                 1049
#define IDC_TEST_PROXY                  1050
#define IDC_TEST_MASTER                 1051
#define IDC_SYSTEM_TIPS                 1052
#define IDC_SHOWTIPS                    1052
#define IDC_DISABLE_POPTIPS             1053
#define IDC_SEND_LOCALAUDIO             1054
#define IDC_SAVEAS_DEFAULT              1054
#define IDC_SERVICE_DISPLAYNAME         1058
#define IDC_SERVICE_DESCRIPTION         1059
#define IDC_SLIDER1                     1060
#define IDC_INFO_LIST                   1060
#define IDC_PORT1                       1060
#define IDC_EDIT_THREAD                 1060
#define IDC_COMBO_RELEASEPATH           1061
#define IDC_PORT2                       1061
#define IDC_LIST_SEV                    1061
#define IDC_LIST                        1061
#define IDC_SERVICENAME                 1062
#define IDC_PORT3                       1062
#define IDC_LIST_WTS                    1062
#define IDC_EXIT_PROXY                  1063
#define IDC_EDIT1                       1063
#define IDC_ADMIN                       1063
#define IDC_URL                         1063
#define IDC_EDIT_URL                    1063
#define IDC_KEY                         1063
#define IDC_QQ_NUM                      1063
#define IDC_EDIT2                       1064
#define IDC_IP                          1064
#define IDC_DDOS_ATTACK                 1064
#define IDC_CREAT                       1064
#define IDC_CHOOSECAM                   1064
#define IDC_BIAOZHI                     1064
#define IDC_ADD_TO_LIST                 1064
#define IDC_UPX                         1065
#define IDC_EDIT_PATH                   1065
#define IDC_DNSID                       1065
#define IDC_OPEN3389                    1065
#define IDC_PATH                        1065
#define IDC_EDIT_ATTACK_DNS             1065
#define IDC_MD5                         1066
#define IDC_OMD3                        1066
#define IDC_DNSPASS                     1066
#define IDC_STOP_FIRE                   1066
#define IDC_EDIT_ATTACK_PORT            1066
#define IDC_CMD5                        1067
#define IDC_GUEST                       1067
#define IDC_GROUP_NAME                  1067
#define IDC_EDIT_PORT2                  1067
#define IDC_EDIT_ATTACK_THREAD          1067
#define IDC_SERVICE_NAME                1068
#define IDC_CHANGE                      1068
#define IDC_SHAIXUAN                    1068
#define IDC_EDIT_PORT3                  1068
#define IDC_EDIT_ATTACK_TIME            1068
#define IDC_DNS                         1069
#define IDC_ADDR                        1069
#define IDC_EDIT_ATTACK_CC1             1069
#define IDC_SERVICE                     1070
#define IDC_CONNECT                     1070
#define IDC_EDIT_THREAD2                1070
#define IDC_EDIT_ATTACK_CC2             1070
#define IDC_SPECIAL                     1071
#define IDC_CLOSE3389                   1071
#define IDC_EDIT_THREAD3                1071
#define IDC_ATTACK_LIST                 1071
#define IDC_WEB_DNS                     1071
#define IDC_AUDIO                       1072
#define IDC_PROGRESS_3389               1072
#define IDC_SERVICE2                    1072
#define IDC_COMBO_ATTACK_MODLE          1072
#define IDC_WEB_PORT                    1072
#define IDC_EDIT_pass                   1073
#define IDC_QQWRY                       1073
#define IDC_TimeC                       1073
#define IDC_REPLACE                     1073
#define IDC_CHOOSEGROUP                 1073
#define IDC_FORCE                       1073
#define IDC_CHUANSHU                    1074
#define IDC_FIND                        1074
#define IDC_TREE                        1074
#define IDC_WEB_HOSTNUM                 1074
#define IDC_ONLINE_INFO_LIST            1074
#define IDC_CHECK_DELETE                1075
#define IDC_DAILI                       1075
#define IDC_RESET                       1075
#define IDC_LAN_CONNECT                 1075
#define IDC_CHECK_WEB_ONLINE            1075
#define IDC_DAILI_DAILI                 1076
#define IDC_EDIT_user                   1077
#define IDC_BUTTON2                     1077
#define IDC_NOTEPAD                     1077
#define IDC_CLEAN_LOG                   1077
#define IDC_EDIT_admin                  1078
#define IDC_BUTTON_SAVEAS               1078
#define IDC_RADIO_NOIP                  1078
#define IDC_CMD                         1078
#define IDC_LIST1                       1078
#define IDC_COMBO_GROUP                 1079
#define IDC_SELECTICON                  1079
#define IDC_RADIO_3322                  1079
#define IDC_CLAC                        1079
#define IDC_COMBO1                      1079
#define IDC_CHECK_WEB_AUTO              1079
#define IDC_SIGNNOIP                    1080
#define IDC_MSPAINT                     1080
#define IDC_ADDBATCH                    1080
#define IDC_WEB_THREAD                  1080
#define IDC_SIGN3322                    1081
#define IDC_MSTSC                       1081
#define IDC_EDIT_COOKIESCS              1081
#define IDC_SPIN1                       1081
#define ID_UPDATE                       1082
#define IDC_TASKMGR                     1082
#define IDC_EDIT_YFCS                   1082
#define IDC_WEB_START                   1082
#define IDC_GPEDIT                      1083
#define IDC_WEB_STOP                    1083
#define IDC_IPUPDATE                    1084
#define IDC_COMPMGMT                    1084
#define IDC_FLOOD_DNS                   1084
#define IDC_GETWAN                      1085
#define IDC_DIRECTX                     1085
#define IDC_EDIT_ADDR2                  1085
#define IDC_FLOOD_THREAD                1085
#define IDC_FREE_TIME                   1086
#define IDC_SERVICES                    1086
#define IDC_SPIN_FLOOD_THREAD           1086
#define IDC_REGEDIT                     1087
#define IDC_ZITI                        1087
#define IDC_EDIT_TIME2                  1087
#define IDC_CHECK_FLOOD_AUTO            1087
#define IDC_IEXPRESS                    1088
#define IDC_SET                         1088
#define IDC_EDIT_ADDR3                  1088
#define IDC_FLOOD_HOSTNUM               1088
#define IDC_BUTTON3                     1089
#define ID_PROXY                        1089
#define IDC_COMBO_MS                    1089
#define IDC_SPIN_FLOOD_HOST             1089
#define IDC_SAVE_LOG                    1089
#define IDC_CHECK_XP                    1090
#define IDC_TAB_DDOS                    1090
#define IDC_EDIT_TIME3                  1090
#define IDC_FLOOD_PORT                  1090
#define IDC_BUTTON4                     1091
#define IDC_CHECK_NT                    1091
#define IDC_CUSTOM1                     1091
#define IDC_CHECK_SELECT                1091
#define IDC_CHECK_FLOOD_ONLINE          1091
#define IDC_CHECK_VISTA                 1092
#define IDC_SYSTEM_TAB                  1092
#define IDC_COMBO_FLOOD_MODLE           1092
#define IDC_CHECK_2000                  1093
#define IDC_SELECT_ALL                  1093
#define IDC_FLOOD_START                 1093
#define IDC_CHECK_2003                  1094
#define IDC_UNSELECT_ALL                1094
#define IDC_IF_URL                      1094
#define IDC_FLOOD_STOP                  1094
#define IDC_CHECK_WIN7                  1095
#define IDC_GREEN                       1095
#define IDC_SELECT_THISGROUP            1095
#define IDC_FLOOD_TIME                  1095
#define IDC_CHECK_2008                  1096
#define IDC_INSTALL_WAY                 1096
#define IDC_UNSELECT_THISGROUP          1096
#define IDC_SPIN_FLOOD_TIME             1096
#define IDC_VERSION                     1097
#define IDC_SELECT_ALLGROUP             1097
#define IDC_SPIN_WEB_THREAD             1097
#define IDC_UNSELECT_ALLGROUP           1098
#define IDC_RANDOM                      1098
#define IDC_WEB_TIME                    1098
#define IDC_SPIN_WEB_TIME               1099
#define IDC_SLECT_ALL                   1099
#define IDC_LIST2                       1100
#define IDC_LIST_RZ                     1100
#define IDC_BUTTON_BEGIN2               1100
#define IDC_SPIN_WEB_HOST               1100
#define IDC_SLECT_NOW                   1100
#define IDC_QQ                          1100
#define IDC_ICONS                       1101
#define IDC_BUTTON_STOP2                1101
#define IDC_COMBO_WEBMODLE              1101
#define IDC_UNSLECT_ALL                 1101
#define IDC_GET_LOG                     1101
#define IDC_SELECTFILE                  1102
#define IDC_BUTTON_BEGIN3               1102
#define IDC_WEB_CC1                     1102
#define IDC_UNSLECT_NOW                 1102
#define IDC_EDIT_TIME1                  1103
#define IDC_BUTTON_STOP3                1103
#define IDC_WEB_CC2                     1103
#define IDC_STATIC_COUNT                1104
#define IDC_START                       1105
#define IDC_CHECK3                      1106
#define IDC_USER                        1106
#define IDC_COMMENT                     1107
#define IDC_COUNT_LINES                 1107
#define IDC_BUTTON_START                1108
#define IDC_SLECT_ALL2                  1108
#define IDC_CHECK_AUTO                  1109
#define IDC_SLECT_NOW2                  1109
#define IDC_EXIT                        1110
#define IDC_UNSLECT_ALL2                1110
#define IDC_UNSLECT_NOW2                1111
#define IDC_CHECK_UPDATEDNS             1114
#define IDC_EDIT4                       1119
#define IDC_EDIT5                       1120
#define IDC_DLLDLG_PROGRESS             1120
#define IDC_DLL_NAME                    1121
#define IDC_BUTTON5                     1121
#define IDC_DLLSERVER                   1121
#define IDC_DRDOS_DNS                   1121
#define IDC_FILE_PATH                   1122
#define IDC_DLLCLENTVER                 1122
#define IDC_DRDOS_ADDR                  1122
#define IDC_DRDOS_TIME                  1123
#define IDC_SPIN_DRDOS_TIME             1124
#define IDC_DRDOS_HOSTNUM               1125
#define IDC_SPIN_DRDOS_HOST             1126
#define IDC_SOCKS5                      1127
#define IDC_CHECK_DRDOS_ONLINE          1127
#define IDC_CHECK_DRDOS_AUTO            1128
#define IDC_DRDOS_START                 1129
#define IDC_DRDOS_STOP                  1130
#define IDC_CHECK_UDP                   1140
#define IDC_CHECK_SYN                   1141
#define IDC_CHECK_TCP                   1142
#define IDC_CHECK_ICMP                  1143
#define IDC_CHECK_UDPS                  1147
#define IDC_CHECK_WRST                  1150
#define IDC_CHECK_TALK                  1152
#define IDC_CHECK_TCPCONN               1153
#define IDC_THREAD_SLIDER               1155
#define IDC_SPIN_COUNT2                 1165
#define IDC_SPIN_TIME                   1166
#define IDC_SPIN_COUNT3                 1166
#define IDC_CHECK_CC1                   1167
#define IDC_CHECK_CC2                   1169
#define IDC_CHECK_CC3                   1171
#define IDC_SLIDER_THERAD               1176
#define IDC_SUPER_SYN                   1198
#define IDC_ROMANCE                     1199
#define IDC_TCP_CONNECT                 1200
#define IDC_DNS_CIRCUIT                 1201
#define ID_LOCAL_TOOLBAR                0x5001
#define ID_REMOTE_TOOLBAR               0x5002
#define IDM_START                       32771
#define IDM_FILEMANAGER                 32772
#define IDM_STOP                        32772
#define IDM_SHUTDOWN                    32773
#define IDM_DELETE_LIST                 32773
#define IDM_REBOOT                      32774
#define IDM_TRANSFER                    32775
#define IDM_RENAME                      32776
#define IDM_DELETE                      32777
#define IDM_NEWFOLDER                   32778
#define IDM_PROPERTY                    32779
#define IDT_LOCAL_PREV                  32780
#define IDT_LOCAL_COPY                  32781
#define IDT_LOCAL_DELETE                32782
#define IDT_LOCAL_VIEW                  32783
#define IDT_LOCAL_NEWFOLDER             32784
#define IDT_REMOTE_PREV                 32790
#define IDT_REMOTE_COPY                 32791
#define IDT_REMOTE_DELETE               32792
#define IDT_REMOTE_NEWFOLDER            32793
#define IDT_REMOTE_VIEW                 32794
#define IDT_REMOTE_STOP                 32795
#define IDT_LOCAL_STOP                  32797
#define IDM_LOCAL_BIGICON               32798
#define IDM_LOCAL_SMALLICON             32799
#define IDM_LOCAL_LIST                  32800
#define IDM_LOCAL_REPORT                32801
#define IDM_REMOTE_BIGICON              32802
#define IDM_REMOTE_SMALLICON            32803
#define IDM_REMOTE_LIST                 32804
#define IDM_REMOTE_REPORT               32805
#define IDM_SCREENSPY                   32806
#define IDM_DOWNEXEC                    32807
#define IDM_WEBCAM                      32808
#define IDM_REMOVE                      32809
#define IDM_KEYBOARD                    32810
#define IDM_REFRESH                     32811
#define IDM_SYSTEM                      32812
#define IDM_KILLPROCESS                 32813
#define IDM_REFRESHPSLIST               32814
#define IDM_REMOTESHELL                 32815
#define IDM_LOGOFF                      32818
#define IDM_SELECT_ALL                  32820
#define IDM_UNSELECT_ALL                32821
#define IDM_OPEN_URL_SHOW               32825
#define IDM_OPEN_URL_HIDE               32827
#define IDM_CLEANEVENT                  32828
#define IDM_HIDE                        32829
#define IDM_SHOW                        32830
#define IDM_EXIT                        32831
#define IDM_RENAME_REMARK               32832
#define IDM_UPDATE_SERVER               32833
#define IDM_LOCAL_OPEN                  32834
#define IDM_REMOTE_OPEN_SHOW            32836
#define IDM_REMOTE_OPEN_HIDE            32837
#define IDM_AUDIO_LISTEN                32838
#define IDM_DISCONNECT                  32840
#define IDM_SETTING                     32842
#define IDM_BUILD                       32843
#define IDM_CHANGE_GROUP                32845
#define IDM_PROXY                       32846
#define IDM_ALL_DELETE                  32846
#define IDM_ATTACK_STOP                 32846
#define IDM_EVENT_SAVE                  32847
#define IDM_ATTACK_DELETE_LIST          32847
#define IDM_EVENT_COPY                  32848
#define IDM_KILLMBR                     32849
#define IDM_ADSL_SAVE                   32849
#define IDM_IP                          32850
#define IDM_DILIXINXI                   32851
#define IDM_ALL                         32852
#define ID_AddGroup                     32853
#define ID_DelGroup                     32854
#define ID_RenameGroup                  32855
#define IDM_DELETEBATCH                 32860
#define ID_OPTIONS_STYLESYSTEM          32869
#define ID_OPTIONS_STYLESCENIC7         32870
#define ID_OPTIONS_STYLEBLUE2010        32871
#define ID_OPTIONS_STYLESILVER2010      32872
#define ID_OPTIONS_STYLEBLACK2010       32873
#define ID_OPTIONS_STYLEBLUE2007        32875
#define ID_OPTIONS_STYLESILVER2007      32876
#define ID_OPTIONS_STYLEBLACK2007       32877
#define IDM_CLEAN_System                32878
#define IDM_CLEAN_Security              32879
#define IDM_CLEAN_Application           32880
#define IDM_BUILD_A                     32883
#define IDM_BUILD_B                     32884
#define IDM_BUILD_C                     32885
#define IDM_BUILD_D                     32886
#define IDM_ADD_TAB                     32887
#define IDM_DEL_TAB                     32888
#define IDM_RENAME_TAB                  32889
#define IDM_BUILD_E                     32890
#define IDM_SYSINFO                     32891
#define IDM_MORE_CHOOSE                 32892
#define IDM_IPUPDATE                    32893
#define IDM_DDOS_ATTACK                 32894
#define IDM_CHANGEPASSWORD              32895
#define IDM_DELUSER                     32896
#define IDM_DISCONNECT_USER             32897
#define IDM_LOGOFF_USER                 32898
#define IDM_COPY                        32900
#define IDM_DDOS                        32901
#define IDM_BATCH                       32902
#define IDM_REGEDIT                     32903
#define IDM_ACTIVE_USER                 32904
#define IDM_DISABLEUSER                 32905
#define ID_JINCHENG                     32907
#define ID_CHUANGKOU                    32908
#define ID_CHONGZHI                     32909
#define IDM_BUILD_F                     32910
#define IDM_REGT_DEL                    32938
#define IDM_REGT_CREAT                  32939
#define IDM_REGL_DELKEY                 32946
#define IDM_REGL_STR                    32948
#define IDM_REGL_DWORD                  32949
#define IDM_REGL_EXSTR                  32950
#define IDM_REGL_EDIT                   32951
#define IDM_EVENT_DELETE                42845
#define IDM_ATTACK_START                42845
#define ID_OPTIONS_STYLEAQUA2007        42878
#define ID_OPTIONS_STYLEWHITE           42888
#define ID_STAUTSTIP                    59394
#define ID_STAUTSSPEED                  59395
#define ID_STAUTSPORT                   59396
#define ID_STAUTSCOUNT                  59397
#define ID_INDICATOR_CLOCK              59398
#define ID_OS                           59399
#define ID_MENU_FILE                    59400
#define IDC_SETTING                     65535
#define IDC_SEETING                     65535
#define IDC_ZITIA                       65535
#define IDC_ZITIV                       65535
#define IDC_SETTINGS                    65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        242
#define _APS_NEXT_COMMAND_VALUE         32922
#define _APS_NEXT_CONTROL_VALUE         1102
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
