// XTPDockingPaneResource.h
//
// (c)1998-2020 Codejock Software, All Rights Reserved.
//
// THIS SOURCE FILE IS THE PROPERTY OF CODEJOCK SOFTWARE AND IS NOT TO BE
// RE-DISTRIBUTED BY ANY MEANS WHATSOEVER WITHOUT THE EXPRESSED WRITTEN
// CONSENT OF CODEJOCK SOFTWARE.
//
// THIS SOURCE CODE CAN ONLY BE USED UNDER THE TERMS AND CONDITIONS OUTLINED
// IN THE XTREME TOOLKIT PRO LICENSE AGREEMENT. CODEJOCK SOFTWARE GRANTS TO
// YOU (ONE SOFTWARE DEVELOPER) THE LIMITED RIGHT TO USE THIS SOFTWARE ON A
// SINGLE COMPUTER.
//
// CONTACT INFORMATION:
// support@codejock.com
// http://www.codejock.com
//
/////////////////////////////////////////////////////////////////////////////

#define XTP_DOCKINGPANE_RESOURCE_FIRST 9475
#define XTP_DOCKINGPANE_RESOURCE_LAST 9529

#define XTP_IDB_DOCKINGPANE_VISIOGRIPPER 9475
#define XTP_IDB_DOCKINGPANE_STICKER_CLIENT 9476
#define XTP_IDB_DOCKINGPANE_STICKERS_BLUE 9477
#define XTP_IDB_DOCKINGPANE_STICKERS_OLIVE 9478
#define XTP_IDB_DOCKINGPANE_STICKERS_SILVER 9479
#define XTP_IDB_DOCKINGPANE_STICKERS_2008 9481

#define XTP_IDB_DOCKINGPANE_STICKERS_VS_2005_100 9482
#define XTP_IDB_DOCKINGPANE_STICKERS_VS_2005_125 9483
#define XTP_IDB_DOCKINGPANE_STICKERS_VS_2005_150 9484
#define XTP_IDB_DOCKINGPANE_STICKERS_VS_2005_200 9485

#define XTP_IDB_DOCKINGPANE_STICKERS_VS_LIGHT_100 9486
#define XTP_IDB_DOCKINGPANE_STICKERS_VS_LIGHT_125 9487
#define XTP_IDB_DOCKINGPANE_STICKERS_VS_LIGHT_150 9488
#define XTP_IDB_DOCKINGPANE_STICKERS_VS_LIGHT_200 9489

#define XTP_IDB_DOCKINGPANE_STICKERS_VS_DARK_100 9490
#define XTP_IDB_DOCKINGPANE_STICKERS_VS_DARK_125 9491
#define XTP_IDB_DOCKINGPANE_STICKERS_VS_DARK_150 9492
#define XTP_IDB_DOCKINGPANE_STICKERS_VS_DARK_200 9493

#define XTP_IDB_DOCKINGPANE_STICKERS_VS_BLUE_100 9494
#define XTP_IDB_DOCKINGPANE_STICKERS_VS_BLUE_125 9495
#define XTP_IDB_DOCKINGPANE_STICKERS_VS_BLUE_150 9496
#define XTP_IDB_DOCKINGPANE_STICKERS_VS_BLUE_200 9497

#define XTP_IDB_DOCKINGPANE_STICKERS_2005 XTP_IDB_DOCKINGPANE_STICKERS_VS_2005_100
#define XTP_IDB_DOCKINGPANE_STICKERS_2010 XTP_IDB_DOCKINGPANE_STICKERS_VS_BLUE_100
#define XTP_IDB_DOCKINGPANE_STICKERS_2012_LIGHT XTP_IDB_DOCKINGPANE_STICKERS_VS_LIGHT_100
#define XTP_IDB_DOCKINGPANE_STICKERS_2012_DARK XTP_IDB_DOCKINGPANE_STICKERS_VS_DARK_100
#define XTP_IDB_DOCKINGPANE_STICKERS_2015_LIGHT XTP_IDB_DOCKINGPANE_STICKERS_VS_LIGHT_100
#define XTP_IDB_DOCKINGPANE_STICKERS_2015_BLUE XTP_IDB_DOCKINGPANE_STICKERS_VS_BLUE_100
#define XTP_IDB_DOCKINGPANE_STICKERS_2015_DARK XTP_IDB_DOCKINGPANE_STICKERS_VS_DARK_100

#define XTP_IDS_DOCKINGPANE_AUTOHIDE 9513
#define XTP_IDS_DOCKINGPANE_CLOSE 9514
#define XTP_IDS_DOCKINGPANE_MAXIMIZE 9515
#define XTP_IDS_DOCKINGPANE_RESTORE 9516
#define XTP_IDS_DOCKINGPANE_MENU 9517
#define XTP_IDS_DOCKINGPANE_SELECTWINDOW_ACTIVETOOLS 9518
#define XTP_IDS_DOCKINGPANE_SELECTWINDOW_ACTIVEFILES 9519
