// Resource.h resources used by PropertyGrid classes.
//
// (c)1998-2020 Codejock Software, All Rights Reserved.
//
// THIS SOURCE FILE IS THE PROPERTY OF CODEJOCK SOFTWARE AND IS NOT TO BE
// RE-DISTRIBUTED BY ANY MEANS WHATSOEVER WITHOUT THE EXPRESSED WRITTEN
// CONSENT OF CODEJOCK SOFTWARE.
//
// THIS SOURCE CODE CAN ONLY BE USED UNDER THE TERMS AND CONDITIONS OUTLINED
// IN THE XTREME TOOLKIT PRO LICENSE AGREEMENT. CODEJOCK SOFTWARE GRANTS TO
// YOU (ONE SOFTWARE DEVELOPER) THE LIMITED RIGHT TO USE THIS SOFTWARE ON A
// SINGLE COMPUTER.
//
// CONTACT INFORMATION:
// support@codejock.com
// http://www.codejock.com
//
/////////////////////////////////////////////////////////////////////////////

#define XTP_PROPERTYGRID_RESOURCE_FIRST 9530
#define XTP_PROPERTYGRID_RESOURCE_LAST 9549

#define XTP_IDR_PROPERTYGRID_TOOLBAR XTP_IDR_PROPERTYGRID_TOOLBAR_100
#define XTP_IDR_PROPERTYGRID_TOOLBAR_100 9530
#define XTP_IDR_PROPERTYGRID_TOOLBAR_125 9531
#define XTP_IDR_PROPERTYGRID_TOOLBAR_150 9532
#define XTP_IDR_PROPERTYGRID_TOOLBAR_200 9533
#define XTP_IDC_PROPERTYGRID_CATEGORIZED 9534
#define XTP_IDC_PROPERTYGRID_ALPHABETIC 9535
#define XTP_IDS_PROPERTYGRID_TRUEFALSE 9536
#define XTP_IDS_PROPERTYGRID_WIDTH 9537
#define XTP_IDS_PROPERTYGRID_HEIGHT 9538
